var AppState = {
    MENU: "MENU",
    USER_SETTINGS: "USER_SETTINGS",
    NEW_GAME_MENU: "NEW_GAME_MENU",
    FIND_RANDOM_OPPONENT: "FIND_RANDOM_OPPONENT",
    SINGLE_PLAYER_GAME: "SINGLE_PLAYER_GAME",
    FB_FRIEND: "FB_FRIEND",
    GAME: "GAME",
    CAMERA_VIEW: "CAMERA_VIEW",
    RANKING: "RANKING",
    REPORT_PHOTO: "REPORT_PHOTO",
    HOW_TO_PLAY: "HOW_TO_PLAY",
    TEST: "TEST"
};

module.exports = AppState;