var AppState = {
    MENU: "MENU",
    USER_SETTINGS: "USER_SETTINGS",
    NEW_GAME_MENU: "NEW_GAME_MENU",
    FIND_RANDOM_OPPONENT: "FIND_RANDOM_OPPONENT",
    SINGLE_PLAYER_GAME: "SINGLE_PLAYER_GAME",
    GAME: "GAME",
    CAMERA_VIEW: "CAMERA_VIEW",
    TEST: "TEST"
};

module.exports = AppState;