var GameState = {
    ANSWER_QUESTION: "ANSWER_QUESTION",
    CHOOSE_PHOTO_TOPIC: "CHOOSE_PHOTO_TOPIC",
    PHOTO: "PHOTO",
    SUMMARY: "SUMMARY",
    LOADING: "LOADING"
};

module.exports = GameState;