var GameState = {
    ANSWER_QUESTION: "ANSWER_QUESTION",
    CHOOSE_PHOTO_TOPIC: "CHOOSE_PHOTO_TOPIC",
    PHOTO: "PHOTO",
    TURN_SUMMARY: "TURN_SUMMARY",
    SUMMARY: "SUMMARY",
    WAITING: "WAITING",
    LOADING: "LOADING",
    DATA_SEND: "DATA_SEND",
    REPORT_PHOTO: "REPORT_PHOTO"
};

module.exports = GameState;